name: Generar EXE para Windows

on:
  push:
    branches: [ main ]  # Se activa cuando subes cambios a la rama main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Cambia a tu versión de Python si es necesario

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Si tienes un archivo requirements.txt, descomenta la línea de abajo:
        pip install -r requirements.txt

    - name: Crear Ejecutable
      run: |
        # Cambia 'tu_script.py' por el nombre real de tu archivo

        # pyinstaller --onefile --windowed app.py
        pyinstaller --onefile --windowed --collect-all PIL --collect-all reportlab --collect-all matplotlib app.py


    - name: Guardar el archivo generado
      uses: actions/upload-artifact@v4
      with:
        name: ejecutable-windows
        path: dist/*.exe